settings:
  email: "your_email@domain.com"
  bulb_ip: "192.168.1.100"
  chromedriver_path: "c:/tools/chromedriver.exe"
status_mappings:
  available:
    status: Available
    color: "0,255,0"  # Green
  busy:
    status: Available
    color: "0,255,0"  # Green
  away:
    status: Available
    color: "0,255,0"  # Green
  focusing:
    status: Available
    color: "0,255,0"  # Green
  do not disturb:
    status: Available
    color: "0,255,0"  # Green
  be right back:
    status: Available
    color: "0,255,0"  # Green
  offline:
    status: Available
    color: "0,255,0"  # Green
  in a call:
    status: Busy
    color: "255,0,0"  # Red
  in a meeting:
    status: Available
    color: "0,255,0"  # Green
  presenting:
    status: Busy
    color: "255,0,0"  # Red
